apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.name" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  PORT: {{ quote .Values.containerPort }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
