apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "task-manager/worker:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: {{ include "worker.name" . }}
