apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
        - name: api
          image: task-manager/worker:v0.1.0
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: worker-env
