services:
  redis:
    image: "redis:alpine"
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
