repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - chart: prometheus-community/prometheus
    name: prometheus
    namespace: monitoring
    version: 27.0
    createNamespace: true

  - chart: grafana/grafana
    name: grafana
    namespace: monitoring
    version: 9.2.10
    createNamespace: true
    values:
      - grafana.values.yaml

  - chart: grafana/loki-stack
    name: loki
    namespace: monitoring
    version: 2.10.2
    createNamespace: true
    values:
      - loki.values.yaml
